version: "3.3"
services:

  mt-build-environment:
    image: summaplatform/mt-build-environment
    build:
      context: ../mt-build-environment
      args:
        GITHASH: ${GITHASH}

  mt-marian-compiled:
    image: summaplatform/mt-marian-compiled
    build:
      context: ../mt-marian-compiled
      args:
        GITHASH: ${GITHASH}

  mt-basic-engine:
    image: summaplatform/mt-basic-engine
    build:
      context: ../mt-basic-engine
      args:
        GITHASH: ${GITHASH}

  mt-engine:
    image: summaplatform/mt-engine
    build:
      context: ../mt-engine
      args:
        GITHASH: ${GITHASH}

  mt-engine-fa-en:
    image: summaplatform/mt-engine-fa-en:${MT_MODEL_VERSION}
    build:
      context: ../mt-engine-with-model
      args:
        MODEL_IMAGE: summaplatform/mt-model-fa-en:${MT_MODEL_VERSION}
        SRCLANG: fa
        TRGLANG: en
        MT_MODEL_PATH: /model
